### ISSUE TITLE
Exception when player joins

### ISSUE THREAD

**Issue by LemADEC** [MassiveCraft/MassiveCore#200]
Using MassiveCore-2.7.4.jar, MassiveTickets-2.7.4.jar and Factions-2.7.4.jar, I see the following exception on console:

```
[00:29:04 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PlayerInventory
[00:29:04 WARN]:        at java.lang.Class.forName0(Native Method)
[00:29:04 WARN]:        at java.lang.Class.forName(Class.java:191)
[00:29:04 WARN]:        at com.massivecraft.massivecore.particleeffect.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:414)
[00:29:04 WARN]:        at com.massivecraft.massivecore.mixin.InventoryMixinDefault.<clinit>(InventoryMixinDefault.java:35)
[00:29:04 WARN]:        at com.massivecraft.massivecore.mixin.Mixin.<clinit>(Mixin.java:35)
[00:29:04 WARN]:        at com.massivecraft.massivecore.util.IdUtil.playerLoginLowest(IdUtil.java:388)
[00:29:04 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:29:04 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[00:29:04 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:29:04 WARN]:        at java.lang.reflect.Method.invoke(Method.java:606)
[00:29:04 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[00:29:04 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[00:29:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[00:29:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[00:29:04 WARN]:        at net.minecraft.server.management.ServerConfigurationManager.attemptLogin(ServerConfigurationManager.java:566)
[00:29:04 WARN]:        at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:130)
[00:29:04 WARN]:        at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:70)
[00:29:04 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:247)
[00:29:04 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[00:29:04 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
[00:29:04 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[00:29:04 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[00:29:04 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[00:29:04 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

Any idea what's causing that?!?

**Comment by LemADEC** [comment]
Any progress to share?

**Comment by i9hdkill** [comment]
Just update to 2.7.5 or downgrade to 2.7.3

**Comment by oloflarsson** [comment]
Cauldron is dead.

**Comment by i9hdkill** [comment]
Still. There are hundreds of modded Forge servers that are relying on cauldron/1.7.10 because sponge isn't ready to replace a cauldron server with many plugins. Not at all. Probably sponge itself, but there aren't that much mods/plugins developed for sponge right now.
There are some unofficial cauldron builds with bugfixes.
http://tcpr.ca/cauldron
I would appreciate if the Massive Plugins are keeping up with the 1.7.10 support.

**Comment by LemADEC** [comment]
kCauldron is the continuation of Cauldron  https://gitlab.prok.pw/Prototik/KCauldron
Sponge is 1.8 so it doesn't address the 1.7.10 support.

**Comment by i9hdkill** [comment]
Not directly but some modpacks are already updated to 1.8. (For example Pixelmon) The only thing that are holding back serveradmins updating to the new Pixelmon 1.8 version are missing sponge plugins.
So I would be great if Massive conitinues to support 1.7.10 until more plugin devs/or plugins in general support sponge.

**Comment by oloflarsson** [comment]
I think the main problem is that none of us developers use Cauldron ourselves and we have loads of ideas we want to code in for ourselves. If an external developer were to make a pull request for Cauldron support then we might add it to the source code, but we will not have the time to do it ourselves.

**Comment by LemADEC** [comment]
A simple option to disable particle effects could do the trick.

**Comment by DarkBlade12** [comment]
The part of code which is causing this exception tries to find the class ```net/minecraft/server/v1_7_R4/PlayerInventory```. However it seems that this class doesn't exist in the expected place, because either the path is something else or this class is not included in Cauldron's server files.

**Comment by ulumulu1510** [comment]
Zzowwa

**Comment by LemADEC** [comment]
MCPC/Cauldron will dynamically remap those classes so we won't see them directly in the jar. This need some dedicated time, can't do that in short term.
