### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by TomPiXX** [MassiveCraft/MassiveCore#202]
[15:30:00 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PlayerInventory
[15:30:00 WARN]:        at java.lang.Class.forName0(Native Method)
[15:30:00 WARN]:        at java.lang.Class.forName(Unknown Source)
[15:30:00 WARN]:        at com.massivecraft.massivecore.particleeffect.ReflectionUtils$PackageType.getClass(ReflectionUt
ils.java:414)
[15:30:00 WARN]:        at com.massivecraft.massivecore.mixin.InventoryMixinDefault.<clinit>(InventoryMixinDefault.java:
35)
[15:30:00 WARN]:        at com.massivecraft.massivecore.mixin.Mixin.<clinit>(Mixin.java:35)
[15:30:00 WARN]:        at com.massivecraft.massivecore.store.SenderEntity.isOffline(SenderEntity.java:97)
[15:30:00 WARN]:        at com.massivecraft.massivecore.store.SenderColl$2.apply(SenderColl.java:142)
[15:30:00 WARN]:        at com.massivecraft.massivecore.store.SenderColl$2.apply(SenderColl.java:139)
[15:30:00 WARN]:        at com.massivecraft.massivecore.store.MStoreUtil.uglySQL(MStoreUtil.java:25)
[15:30:00 WARN]:        at com.massivecraft.massivecore.store.Coll.getAll(Coll.java:141)
[15:30:00 WARN]:        at com.massivecraft.massivecore.store.SenderColl.getAllOffline(SenderColl.java:138)
[15:30:00 WARN]:        at com.massivecraft.factions.entity.MPlayerColl.considerRemovePlayerMillis(MPlayerColl.java:53)
[15:30:00 WARN]:        at com.massivecraft.factions.task.TaskPlayerDataRemove.invoke(TaskPlayerDataRemove.java:36)
[15:30:00 WARN]:        at com.massivecraft.massivecore.ModuloRepeatTask.run(ModuloRepeatTask.java:76)
[15:30:00 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[15:30:00 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.ja
va:346)
[15:30:00 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862)
[15:30:00 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[15:30:00 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[15:30:00 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[15:30:00 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by oloflarsson** [comment]
Cauldron is dead.

**Comment by ChenYuWuAi** [comment]
.
