### ISSUE TITLE
A constantly Warn un my server, i didn't know why

### ISSUE THREAD

**Issue by SrBurgman** [MassiveCraft/MassiveCore#235]
The error is this. Constantly.

[15:53:44][Server thread/WARN]: [MassiveCore] Task #4880 for MassiveCore v2.8.0 generated an exception
java.lang.NoSuchMethodError:org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
atcom.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_8.transferUnbreakable(ItemStackAdapterInnerV1_8.java:66) ~[?:?]
atcom.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_8.transferMetaUnspecific(ItemStackAdapterInnerV1_8.java:54) ~[?:?]
atcom.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_7.transferMeta(ItemStackAdapterInnerV1_7.java:226) ~[?:?]
atcom.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_7.transferAll(ItemStackAdapterInnerV1_7.java:140) ~[?:?]
atcom.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_7.erialize(ItemStackAdapterInnerV1_7.java:95) ~[?:?]
at com.massivecraft.massivecore.adapter.ItemStackAdapter.serialize(ItemStackAdapter.java:63) ~[?:?]
at com.massivecraft.massivecore.adapter.ItemStackAdapter.serialize(ItemStackAdapter.java:1) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:71) ~[?:?]
atcom.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[?:?]
atcom.massivecraft.massivecore.xlib.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:1) ~[?:?]
atcom.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
atcom.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:100) ~[?:?]
atcom.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:220) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.Gson.toJson(Gson.java:600) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.Gson.toJsonTree(Gson.java:493) ~[?:?]
at com.massivecraft.massivecore.store.Coll.saveToRemoteFixed(Coll.java:502) ~[?:?]
at com.massivecraft.massivecore.store.Coll.syncIdFixed(Coll.java:702) ~[?:?]
at com.massivecraft.massivecore.store.CollAbstract.syncIdFixed(CollAbstract.java:185) ~[?:?]
at com.massivecraft.massivecore.store.Coll.syncIdentified(Coll.java:778) ~[?:?]
at com.massivecraft.massivecore.store.Coll.onTick(Coll.java:812) ~[?:?]
at com.massivecraft.vampire.entity.UConfColl.onTick(UConfColl.java:25) ~[?:?]
at com.massivecraft.massivecore.EngineCollTick.run(EngineCollTick.java:41) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit.jar:git-Bukkit-5e85956]
atorg.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit.jar:git-Bukkit-5e85956]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [craftbukkit.jar:git-Bukkit-5e85956]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit.jar:git-Bukkit-5e85956]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit.jar:git-Bukkit-5e85956]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit.jar:git-Bukkit-5e85956]

**Comment by SrBurgman** [comment]
I believe its problem of Vampire

**Comment by OtakuHalo** [comment]
If I may assist, I believe your problem may be that you are running Bukkit rather than Spigot. My thread [here](https://github.com/MassiveCraft/MassiveCore/issues/238) was about a similar exception, if not the same one. It can be fixed by, as explained by the amazing person who helped me, using spigot rather than Bukkit. Figured I'd help since my problem was just fixed.

**Comment by ulumulu1510** [comment]
Yes, indeed it is the same issue as on the issue mentioned above. :) Running the spigot.jar instead of the bukkit.jar is the solution and resolves the spamming. For more information visit the other issue mentioned above.
