### ISSUE TITLE
Exception in MassiveCore Task #9

### ISSUE THREAD

**Issue by mamoran** [MassiveCraft/MassiveCore#237]
Generates this issue continuously when anyone is on the server:
[22:37:34 WARN]: [MassiveCore] Task #9 for MassiveCore v2.8.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
        at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_8.transferUnbreakable(ItemStackAdapterInnerV1_8.java:66) ~[?:?]
        at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_8.transferMetaUnspecific(ItemStackAdapterInnerV1_8.java:54) ~[?:?]
        at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_7.transferMeta(ItemStackAdapterInnerV1_7.java:226) ~[?:?]
        at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_7.transferAll(ItemStackAdapterInnerV1_7.java:140) ~[?:?]
        at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_7.erialize(ItemStackAdapterInnerV1_7.java:95) ~[?:?]
        at com.massivecraft.massivecore.adapter.ItemStackAdapter.serialize(ItemStackAdapter.java:63) ~[?:?]
        at com.massivecraft.massivecore.adapter.ItemStackAdapter.serialize(ItemStackAdapter.java:1) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:71) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:1) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:100) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:220) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.Gson.toJson(Gson.java:600) ~[?:?]
        at com.massivecraft.massivecore.xlib.gson.Gson.toJsonTree(Gson.java:493) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.saveToRemoteFixed(Coll.java:497) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.syncIdFixed(Coll.java:697) ~[?:?]
        at com.massivecraft.massivecore.store.CollAbstract.syncIdFixed(CollAbstract.java:200) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.syncIdentified(Coll.java:773) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.onTick(Coll.java:807) ~[?:?]
        at com.massivecraft.vampire.entity.UConfColl.onTick(UConfColl.java:25) ~[?:?]
        at com.massivecraft.massivecore.EngineCollTick.run(EngineCollTick.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.8.8.jar:git-Bukkit-53fac9f]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.8.8.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [craftbukkit-1.8.8.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.8.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit-1.8.8.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit-1.8.8.jar:git-Bukkit-53fac9f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]

It just repeats every few seconds.

[22:37:39 WARN]: [MassiveCore] Task #9 for MassiveCore v2.8.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
        at com.massivecraft.massivecore.adapter.ItemStackAdapterInnerV1_8.transferUnbreakable(ItemStackAdapterInnerV1_8.java:66) ~[?:?]...

If this is not a MassiveCore/Massivecraft issue then who's issue is it?
Who would I file this against?

**Comment by magnusulf** [comment]
It seems you run a bucket 1.8 server which is not Spigot. Is that correct?
In that case, could you link us to where you got your server software from?

**Comment by mamoran** [comment]
https://www.spigotmc.org/  They have
      CraftBukkit too.
      
      There are quite a few steps involved
      On 10/9/2015 5:23 AM, Madus wrote:
    
    
      It seems you run a bucket 1.8 server which is not Spigot. Is
        that correct?
        In that case, could you link us to where you got your server
        software from?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by ulumulu1510** [comment]
You should run the spigot.jar instead. This jar provides the methods needed so the console spam doesn't happen.
