### ISSUE TITLE
Poller error forMStore ModificationPollerRemote

### ISSUE THREAD

**Issue by L4BORG** [MassiveCraft/MassiveCore#244]
```
[00:52:57] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[00:52:57] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[00:52:57] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	... 3 more
[00:52:57] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[00:52:57] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[00:52:57] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	... 3 more
[00:52:57] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[00:52:57] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[00:52:57] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	... 3 more
[00:52:57] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[00:52:57] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[00:52:57] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	... 3 more
[00:52:57] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[00:52:57] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[00:52:57] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	... 3 more
[00:52:57] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[00:52:57] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[00:52:57] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	... 3 more
[00:52:57] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[00:52:57] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[00:52:57] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	... 3 more
[00:52:57] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[00:52:57] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[00:52:57] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	... 3 more
[00:52:57] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[00:52:57] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[00:52:57] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[00:52:57] [MStore ModificationPollerRemote/WARN]: 	... 3 more
```

any idea what is going on? o.0

**Comment by MrEvilChaos** [comment]
I too am receiving this error causing massive log files to happen.
[19:32:01] [MStore ModificationPollerRemote/INFO]: Poller error forMStore ModificationPollerRemote
[19:32:01] [MStore ModificationPollerRemote/WARN]: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
[19:32:01] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:230)
[19:32:01] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DbAbstract.supportsPusher(DbAbstract.java:83)
[19:32:01] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerRemote.getMillisBetweenPoll(ModificationPollerRemote.java:30)
[19:32:01] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.ModificationPollerAbstract.run(ModificationPollerAbstract.java:38)
[19:32:01] [MStore ModificationPollerRemote/WARN]: Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
[19:32:01] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[19:32:01] [MStore ModificationPollerRemote/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[19:32:01] [MStore ModificationPollerRemote/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusher(DriverFlatfile.java:226)
[19:32:01] [MStore ModificationPollerRemote/WARN]: 	... 3 more

**Comment by L4BORG** [comment]
More info...

```
user@m05:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:        8
Codename:       jessie
user@m05:~$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
user@m05:~$
```

and SAMSUNG MZ7LM240 SSD's... if this helps.

**Comment by ulumulu1510** [comment]
I am asuming you are using 2.8.3 MassiveCore, right?

@magnusulf

**Comment by L4BORG** [comment]
Yes, that was 2.8.3 after downgrade to 2.8.2 everything went back to normal.

**Comment by magnusulf** [comment]
Use 2.8.5
