### ISSUE TITLE
Bug with plugin faction 

### ISSUE THREAD

**Issue by mantalo35** [MassiveCraft/MassiveCore#246]
if i want claim i land i can't 
the log : 

[09:46:35] [Server thread/INFO]: mantalo35 issued server command: /f claim

[09:46:36] [Server thread/INFO]: [MassiveCore 2.8.5] If you use 1.8.X or above, please report this error at https://github.com/MassiveCraft/MassiveCore/issues

[09:46:36] [Server thread/WARN]: com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket$VersionIncompatibleException: Your current bukkit version seems to be incompatible with this library

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1401)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket.getVersion(ParticleEffect.java:1414)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.nms.NmsAbstract.getCurrentVersion(NmsAbstract.java:63)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.nms.NmsAbstract.isAvailableForCurrentVersion(NmsAbstract.java:73)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.nms.NmsAbstract.<init>(NmsAbstract.java:33)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.nms.NmsPacket.<init>(NmsPacket.java:15)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.nms.NmsPacket.<clinit>(NmsPacket.java:21)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.mixin.MessageMixinDefault.messageOne(MessageMixinDefault.java:95)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.mixin.Mixin.messageOne(Mixin.java:367)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.command.MassiveCommand.message(MassiveCommand.java:1199)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.command.HelpCommand.perform(HelpCommand.java:61)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:828)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.command.MassiveCommand.perform(MassiveCommand.java:879)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:828)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:785)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:869)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61)

[09:46:36] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)

[09:46:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:718)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1328)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1110)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:811)

[09:46:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:671)

[09:46:36] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

[09:46:36] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutWorldParticles

[09:46:36] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)

[09:46:36] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:259)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.particleeffect.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:414)

[09:46:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1395)

[09:46:36] [Server thread/WARN]: 	... 29 more

[09:46:38] [Server thread/INFO]: mantalo35 issued server command: /f claim one

[09:47:10] [Server thread/INFO]: mantalo35 lost connection: Internal Exception: java.io.IOException: Connexion ré-initialisée par le correspondant

[09:47:10] [Server thread/INFO]: mantalo35 left the game.

**Comment by ulumulu1510** [comment]
The Bug is known, in case you use a Cauldron/KCauldron server. If that is not the case, please report back.


When you report back, make sure to include you MassiveCore and Factions Version.

**Comment by mantalo35** [comment]
I have cauldron server ! 
You have the answer for This bug ?

**Comment by ulumulu1510** [comment]
Cauldron is not supported at this point. Iz is however being worked on by Markehme. He is investigating what in Cauldron causes this issue and will hopefully be able to fix it. For future tracking, go to the issue from factions and look for the topic : "CommandSender link severed"

**Comment by MarkehMe** [comment]
See https://github.com/MassiveCraft/Factions/issues/940
