### ISSUE TITLE
java.io.IOException: User limit of inotify instances reached or too many open files

### ISSUE THREAD

**Issue by L4BORG** [MassiveCraft/MassiveCore#248]
```
[20:05:07] [Server thread/INFO]: [MassiveCore] Enabling MassiveCore v2.8.6
[20:05:07] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.6[0;36;22m] [0;33;1m=== ENABLE START ===[m
[20:05:07] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.6[0;36;22m] [0;33;1m[0;33;1mLoading Cachefile datas...[m
[20:05:07] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.6[0;36;22m] [0;33;1m[0;33;1mLoading Onlineplayer datas...[m
[20:05:07] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.6[0;36;22m] [0;33;1m[0;33;1mLoading Registry datas...[m
[20:05:07] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.6[0;36;22m] [0;33;1m[0;33;1mSaving Cachefile...[m
[20:05:07] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.6[0;36;22m] [0;33;1m[0;33;1mSetup of IdUtil took [0;35;1m4[0;33;1mms.[m
[20:05:07] [Server thread/WARN]: java.io.IOException: User limit of inotify instances reached or too many open files
[20:05:07] [Server thread/WARN]: 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
[20:05:07] [Server thread/WARN]: 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
[20:05:07] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.supportsPusherCalc(DriverFlatfile.java:229)
[20:05:07] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.<init>(DriverFlatfile.java:222)
[20:05:07] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.DriverFlatfile.<clinit>(DriverFlatfile.java:35)
[20:05:07] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.MStore.<clinit>(MStore.java:41)
[20:05:07] [Server thread/WARN]: 	at com.massivecraft.massivecore.MultiverseColl.<init>(MultiverseColl.java:16)
[20:05:07] [Server thread/WARN]: 	at com.massivecraft.massivecore.MultiverseColl.<clinit>(MultiverseColl.java:12)
[20:05:07] [Server thread/WARN]: 	at com.massivecraft.massivecore.MassiveCore.onEnable(MassiveCore.java:223)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:768)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:556)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[20:05:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[20:05:07] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:05:07] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:773)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[20:05:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[20:05:07] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:05:07] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.6[0;36;22m] [0;33;1m[0;32;1mActivated [0;33;1mintegration with [0;35;1mVault[m
[20:05:07] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.6[0;36;22m] [0;33;1m=== ENABLE [0;32;1mCOMPLETE [0;33;1m(Took [0;35;1m94ms[0;33;1m) ===[m
```

**Comment by MarkehMe** [comment]
This doesn't appear to be a MassiveCore issue, however there does appear to be a limitation on your server. 

```User limit of inotify instances reached or too many open files```

Judging by your error code you're on a Linux machine.

This thread here appears to explain the issue and give a solution: http://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached

**Comment by L4BORG** [comment]
Running almost default config with Debian 8.3 + Oracle Java 8?

Also I did some testing, this won't happen on "normal startup" but it will start happening after a few /reload-s.

So my guess would be that MassiveCore is now not closing files till restart and thus /reload is bugged?

This happened on testing server with almost no data, default Factions/MassiveCore config, only 1 faction and 2 players.

**Comment by ulumulu1510** [comment]
Reload breaks loads of plugins, MassiveCore is one of them. Reloading is deprecated, you should not use it at all.
