### ISSUE TITLE
[Server thread/ERROR]: Error occurred while enabling Factions v2.8.6 (Is it up to date?)

### ISSUE THREAD

**Issue by Mrfreeze56** [MassiveCraft/MassiveCore#249]
i have a problem: since 
a while the plugin faction and the plugin creativegates doesn't work i have the log of faction but i can't find the log for creativegates but i think it's the same problem

log :
`[12:12:40] [Server thread/ERROR]: Error occurred while enabling Factions v2.8.6 (Is it up to date?)
com.massivecraft.massivecore.xlib.gson.JsonSyntaxException: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated object at line 3 column 24 path $.description
at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:57) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:84) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:59) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
at com.massivecraft.massivecore.store.DriverFlatfile.loadFileJson(DriverFlatfile.java:167) ~[?:?]
at com.massivecraft.massivecore.store.DriverFlatfile.loadFile(DriverFlatfile.java:154) ~[?:?]
at com.massivecraft.massivecore.store.DriverFlatfile.loadAll(DriverFlatfile.java:193) ~[?:?]
at com.massivecraft.massivecore.store.DbAbstract.loadAll(DbAbstract.java:68) ~[?:?]
at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:910) ~[?:?]
at com.massivecraft.massivecore.store.Coll.init(Coll.java:982) ~[?:?]
at com.massivecraft.factions.entity.FactionColl.init(FactionColl.java:44) ~[?:?]
at com.massivecraft.factions.Factions.onEnable(Factions.java:139) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-c3c767f-33d5de3]
at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins_1.8.8_Java_7.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-c3c767f-33d5de3]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-c3c767f-33d5de3]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-c3c767f-33d5de3]
at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-c3c767f-33d5de3]
at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-c3c767f-33d5de3]
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-c3c767f-33d5de3]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot.jar:git-Spigot-c3c767f-33d5de3]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: com.massivecraft.massivecore.xlib.gson.stream.MalformedJsonException: Unterminated object at line 3 column 24 path $.description
at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.syntaxError(JsonReader.java:1574) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.doPeek(JsonReader.java:496) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.stream.JsonReader.hasNext(JsonReader.java:419) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:1) ~[?:?]
at com.massivecraft.massivecore.xlib.gson.internal.Streams.parse(Streams.java:45) ~[?:?]
... 23 more`

**Comment by magnusulf** [comment]
A factions file has wrong json syntax. Delete that file.
