### ISSUE TITLE
Error Loading Mcore

### ISSUE THREAD

**Issue by stapleshotz** [MassiveCraft/MassiveCore#255]
After installing Mcore version 2.8.8, I get this error on startup. I'm using CraftBukkit version git-Bukkit-f631379 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

Factions seems to be functioning fine, but /mcore does nothing. I also still get the mcore sponsored messages.

Just tested out Mcore 2.8.7Beta and it loads just fine.

> [16:28:26 INFO]: [MassiveCore] Enabling MassiveCore v2.8.8
[16:28:26 INFO]: [MassiveCore 2.8.8] === ENABLE START ===
[16:28:26 INFO]: [MassiveCore 2.8.8] ºeLoading Cachefile datas...
[16:28:26 INFO]: [MassiveCore 2.8.8] ºeLoading Onlineplayer datas...
[16:28:26 INFO]: [MassiveCore 2.8.8] ºeLoading Registry datas...
[16:28:26 INFO]: [MassiveCore 2.8.8] ºeSaving Cachefile...
[16:28:26 INFO]: [MassiveCore 2.8.8] ºeSetup of IdUtil took ºd15ºems.
[16:28:26 ERROR]: Error occurred while enabling MassiveCore v2.8.8 (Is it up to date?)
java.lang.NullPointerException
        at com.massivecraft.massivecore.engine.EngineMassiveCoreSponsor.inform(EngineMassiveCoreSponsor.java:82) ~[?:?]
        at com.massivecraft.massivecore.engine.EngineMassiveCoreSponsor.setActiveInner(EngineMassiveCoreSponsor.java:45) ~[?:?]
        at com.massivecraft.massivecore.Engine.setActive(Engine.java:72) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:175) ~[?:?]
        at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:206) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:121) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[BUKKIT.jar:git-Bukkit-f631379]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [BUKKIT.jar:git-Bukkit-f631379]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [BUKKIT.jar:git-Bukkit-f631379]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346) [BUKKIT.jar:git-Bukkit-f631379]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318) [BUKKIT.jar:git-Bukkit-f631379]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.<init>(CraftServer.java:256) [BUKKIT.jar:git-Bukkit-f631379]
        at net.minecraft.server.v1_9_R1.PlayerList.<init>(PlayerList.java:69) [BUKKIT.jar:git-Bukkit-f631379]
        at net.minecraft.server.v1_9_R1.DedicatedPlayerList.<init>(SourceFile:14) [BUKKIT.jar:git-Bukkit-f631379]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:182) [BUKKIT.jar:git-Bukkit-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [BUKKIT.jar:git-Bukkit-f631379]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]

**Comment by oloflarsson** [comment]
Thank you for reporting this. It is fixed in this commit: https://github.com/MassiveCraft/MassiveCore/commit/0fd3a8a3633539a4776d05c889f1add5cbcccb47

**Comment by oloflarsson** [comment]
You can also go ahead and update to 2.8.8 now. I could fix this error through the sponsor API by temporarily disabling the in game announcements. I will also release 2.8.9 soon to fix this issue in a more proper manner.

**Comment by stapleshotz** [comment]
Yep, that fixed it! Thanks for the quick response!
