### ISSUE TITLE
1.7.10 up to date ?

### ISSUE THREAD

**Issue by iArkadia** [MassiveCraft/MassiveCore#259]
[19:23:15] [Server thread/INFO]: [MassiveCore] Enabling MassiveCore v2.8.10
[19:23:15] [Server thread/INFO]: [MassiveCore 2.8.10] === ENABLE START ===
[19:23:15] [Server thread/INFO]: [MassiveCore 2.8.10] Loading Cachefile datas...
[19:23:16] [Server thread/INFO]: [MassiveCore 2.8.10] Loading Onlineplayer datas...
[19:23:16] [Server thread/INFO]: [MassiveCore 2.8.10] Loading Registry datas...
[19:23:16] [Server thread/INFO]: [MassiveCore 2.8.10] Saving Cachefile...
[19:23:16] [Server thread/INFO]: [MassiveCore 2.8.10] Setup of IdUtil took 730ms.
[19:23:16] [Server thread/INFO]: [MassiveCore 2.8.10] Activated Integration IntegrationVault
[19:23:16] [Server thread/ERROR]: Error occurred while enabling MassiveCore v2.8.10 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/entity/Rabbit$Type
	at com.massivecraft.massivecore.command.type.RegistryType.registerAll(RegistryType.java:208) ~[?:?]
	at com.massivecraft.massivecore.command.type.RegistryType.<clinit>(RegistryType.java:157) ~[?:?]
	at com.massivecraft.massivecore.command.editor.CommandEditSingleton.getType(CommandEditSingleton.java:51) ~[?:?]
	at com.massivecraft.massivecore.command.editor.CommandEditSingleton.<init>(CommandEditSingleton.java:16) ~[?:?]
	at com.massivecraft.massivecore.command.massivecore.CmdMassiveCore.<init>(CmdMassiveCore.java:34) ~[?:?]
	at com.massivecraft.massivecore.command.massivecore.CmdMassiveCore.<clinit>(CmdMassiveCore.java:20) ~[?:?]
	at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:240) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:124) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-PaperSpigot-43]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-43]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot.jar:git-PaperSpigot-43]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:477) [spigot.jar:git-PaperSpigot-43]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:395) [spigot.jar:git-PaperSpigot-43]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:170) [spigot.jar:git-PaperSpigot-43]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:493) [spigot.jar:git-PaperSpigot-43]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-43]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Rabbit$Type
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-PaperSpigot-43]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-PaperSpigot-43]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
	... 16 more

**Comment by SirFaizdat** [comment]
You're attempting to run MassiveCore 2.8.10 on a Minecraft 1.7.10 server. Try upgrading Spigot to the latest version (1.9.2).

**Comment by iArkadia** [comment]
No, my server is in 1.7.10 this is the best version i don't want update spigot i just want fix massivecore

**Comment by magnusulf** [comment]
We do officially support 1.7.10, so this should be investigated and fixed.

**Comment by SirFaizdat** [comment]
It's looking for org.bukkit.entity.Rabbit.Type, but rabbits don't exist yet in 1.7.x versions. Perhaps [this line] (https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/command/type/RegistryType.java#L208) should only run when the server version is 1.8+?

**Comment by SirFaizdat** [comment]
I did some testing and found that 1.7.10 support works up to MassiveCore v2.8.7Beta. I [compared the code](https://github.com/MassiveCraft/MassiveCore/compare/ab533bbd2b6cd12ffb8870a25408ad99839d1caa...ef9f73c8776ec16e99f4f6b84dc6283286a788e9) between 2.8.7 and 2.8.8, and confirmed that adding rabbits to the RegistryType system isn't going to work so well with 1.7.10.

So, there are two solutions I can see: either 1.7.10 support is dropped, or the code is reworked so that the rabbit type is only called on 1.8+ versions.
