### ISSUE TITLE
Help with trying to update the plugin

### ISSUE THREAD

**Issue by SCOTSChief** [MassiveCraft/MassiveCore#261]
I need some help my server said I need to update the plugin and I do not know how can you please help?

Here is the log i got from my server.

Error occurred while enabling MassiveCore v2.8.10 (Is it up to date?)

java.lang.NoClassDefFoundError: org\/bukkit\/entity\/Rabbit

	at com.massivecraft.massivecore.command.type.RegistryType.registerAll(RegistryType.java:208) ~[?:?]

	at com.massivecraft.massivecore.command.type.RegistryType.(RegistryType.java:157) ~[?:?]

	at com.massivecraft.massivecore.command.editor.CommandEditSingleton.getType(CommandEditSingleton.java:51) ~[?:?]

	at com.massivecraft.massivecore.command.editor.CommandEditSingleton.(CommandEditSingleton.java:16) ~[?:?]

	at com.massivecraft.massivecore.command.massivecore.CmdMassiveCore.(CmdMassiveCore.java:34) ~[?:?]

	at com.massivecraft.massivecore.command.massivecore.CmdMassiveCore.(CmdMassiveCore.java:20) ~[?:?]

	at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:240) ~[?:?]

	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:124) ~[?:?]

	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.55]

	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.55]

	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.55]

	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1614.55]

	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1614.55]

	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]

	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]

	at net.minecraft.world.World.(World.java:367) [ahb.class:?]

	at net.minecraft.world.WorldServer.(WorldServer.java:162) [mt.class:?]

	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:369) [MinecraftServer.class:?]

	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]

	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_03]

Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Rabbit

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:395) ~[PluginClassLoader.class:1.7.10-1614.55]

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.55]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:1.7.0_03]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:1.7.0_03]

	... 21 more

**Comment by magnusulf** [comment]
You are running 1.7.10 I suppose. This will be fixed with the next update.

**Comment by SCOTSChief** [comment]
Ok thanks also i am using thermos when i try claim lad it said i was using cauldron and thermos has spigot as well. Also when is the next update.
