### ISSUE TITLE
issues starting up on paper spigot 916 (10.2)

### ISSUE THREAD

**Issue by avatario** [MassiveCraft/MassiveCore#285]
[18:06:59 INFO]: Using default channel type
[18:07:01 ERROR]: Could not load 'plugins\MassiveLagAgent.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:299) [patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:207) [patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:590) [patched_1.10.2.jar:git-Paper-916]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more
[18:07:02 INFO]: Set PluginClassLoader as parallel capable
[18:07:02 INFO]: Plugin cannot be startet correctly, because World Guard isn't loaded
[18:07:02 ERROR]: Could not load 'plugins\MassiveCore.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:299) [patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:207) [patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:590) [patched_1.10.2.jar:git-Paper-916]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:123) ~[patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67) ~[patched_1.10.2.jar:git-Paper-916]
        at com.massivecraft.massivecore.MassivePlugin.<init>(MassivePlugin.java:21) ~[?:?]
        at com.massivecraft.massivecore.MassiveCore.<init>(MassiveCore.java:81) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_101]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.10.2.jar:git-Paper-916]
        ... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:126) ~[patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67) ~[patched_1.10.2.jar:git-Paper-916]
        at com.nitnelave.CreeperHeal.CreeperHeal.<init>(CreeperHeal.java:26) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_101]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.10.2.jar:git-Paper-916]
        ... 6 more
[18:07:03 ERROR]: Could not load 'plugins\CreativeGates.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MassiveCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:222) [patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:299) [patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:207) [patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:590) [patched_1.10.2.jar:git-Paper-916]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[18:07:03 ERROR]: Could not load 'plugins\MassiveLag.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MassiveCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:222) [patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:299) [patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:207) [patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:590) [patched_1.10.2.jar:git-Paper-916]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

server - https://ci.destroystokyo.com/job/PaperSpigot/916/

**Comment by oloflarsson** [comment]
MassiveLagAgent is not a plugin. It's an agent. Please read the information on the thread on the spigot forums.

**Comment by avatario** [comment]
massive agent was a small part of the error.
Massivecore is saying its already running and it shouldn't. there is only one copy of it.

[18:07:02 ERROR]: Could not load 'plugins\MassiveCore.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.10.2.jar:git-Paper-916]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.10.2.jar:git-Paper-916]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.10.2.jar:git-Paper-916]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:299) [patched_1.10.2.jar:git-Paper-916]
at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:207) [patched_1.10.2.jar:git-Paper-916]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:590) [patched_1.10.2.jar:git-Paper-916]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:123) ~[patched_1.10.2.jar:git-Paper-916]
at org.bukkit.plugin.java.JavaPlugin.(JavaPlugin.java:67) ~[patched_1.10.2.jar:git-Paper-916]
at com.massivecraft.massivecore.MassivePlugin.(MassivePlugin.java:21) ~[?:?]
at com.massivecraft.massivecore.MassiveCore.(MassiveCore.java:81) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_101]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_101]
at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_101]
at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:77) ~[patched_1.10.2.jar:git-Paper-916]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.10.2.jar:git-Paper-916]
... 6 more
