### ISSUE TITLE
Error on Spigot 1.11.2. Please Help.

### ISSUE THREAD

**Issue by TheIntelloBox** [MassiveCraft/MassiveCore#294]
[11:02:45] [Server thread/ERROR]: Error occurred while enabling Factions v2.10.0 (Is it up to date?)
java.lang.NullPointerException
	at java.util.TreeMap.put(TreeMap.java:563) ~[?:1.8.0_72]
	at java.util.TreeSet.add(TreeSet.java:255) ~[?:1.8.0_72]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:83) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:810) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:875) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson$1.deserialize(Gson.java:128) ~[?:?]
	at com.massivecraft.massivecore.adapter.AdapterMassiveX.deserialize(AdapterMassiveX.java:104) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:59) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:104) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:197) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:104) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:197) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:810) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:875) ~[?:?]
	at com.massivecraft.massivecore.xlib.gson.Gson.fromJson(Gson.java:848) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.loadFromRemoteFixed(Coll.java:517) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:931) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:1072) ~[?:?]
	at com.massivecraft.factions.entity.MConfColl.setActive(MConfColl.java:32) ~[?:?]
	at com.massivecraft.factions.Factions.onEnableInner(Factions.java:133) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:75) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

```

**Comment by MarkehMe** [comment]
The following lines have a comma but they shouldn't because they're the last item:
- 15
- 28
- 41
- 54


You can paste your JSON file [into this website](http://jsonlint.com/) to validate it.

**Comment by TheIntelloBox** [comment]
Nice thanks. :)

I have a question : Could you add custom messages and custom help messages ?

**Comment by MarkehMe** [comment]
No worries! Happy to help.

Thats a cool idea. I believe a locale system is planned, which will allow you to modify help messages (and all messages). Keep a look out!

**Comment by TheIntelloBox** [comment]
Oh nice, when do you think ?
