### ISSUE TITLE
'Unsupported Operation' Message When Player Logs Off

### ISSUE THREAD

**Issue by SilverKytten** [MassiveCraft/MassiveCore#297]
I assume the affected plugin is MassiveCore, itself, but I could be wrong?

**Describe your environment**

* Affected Plugin version: 
2.9.0

* MassiveCore version: 
2.9.0

* Spigot version: 
Not Spigot: 
This server is running Thermos | https://github.com/CyberdyneCC/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10)

* Config pastebin: 
I'm not sure which config to include, there are quite a few of them?

Here's my default MassiveCore config, do you need the others?
```
  "serverid": "62a088ce-96eb-4f57-9343-dd19667acca9",
  "dburi": "default",
  "alias2uri": {
    "default": "flatfile",
    "flatfile": "flatfile://mstore",
    "mongodb": "mongodb://localhost:27017/mstore"
  }
}
```

**Steps to reproduce this bug**

  1. Player logs off

This has been happening for quite a while, I just haven't had the time to report it. I'd like to know if it's an issue with this version of the plugin or an issue with my environment, before updating to the new version.

**Observed results**

```
[MassiveCore] Task #1174 for MassiveCore v2.9.0 generated an exception
java.lang.UnsupportedOperationException: not implemented
        at com.massivecraft.massivecore.mixin.Mixin.notImplemented(Mixin.java:183) ~[?:?]
        at com.massivecraft.massivecore.nms.NmsBoard.isEqualsImplemented(NmsBoard.java:104) ~[?:?]
        at com.massivecraft.massivecore.nms.NmsBoard.createObjectiveSet(NmsBoard.java:115) ~[?:?]
        at com.massivecraft.massivecore.util.BoardUtil.getTemporaryObjectives(BoardUtil.java:88) ~[?:?]
        at com.massivecraft.massivecore.util.BoardUtil.clean(BoardUtil.java:237) ~[?:?]
        at com.massivecraft.massivecore.util.BoardUtil$1.run(BoardUtil.java:260) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Expected results**

No error spam? Nothing, basically.

**Comment by MrDienns** [comment]
It shouldn't be anything critical. That's a class controlling a scoreboard, which is if I recall correctly, not added in 1.7.x yet. I'm not sure why MassiveCraft decides to throw an error instead when they can just disable it. But again, it shouldn't be anything critical

**Comment by oloflarsson** [comment]
Thermos is no longer developed and Minecraft 1.7 is a very outdated server version. It's doubtful we will ever fix this ticket I'm afraid. Feel free to add support through a pull request yourself if you want Thermos supported.

**Comment by oloflarsson** [comment]
I'm afraid I'll now close this issue. Thermos is abandoned by it's authors and only ~3% of servers run it (https://bstats.org/global/bukkit). That does not mean I'm agains supporting Thermos. Feel free to code a pull request adding support at any time.
