### ISSUE TITLE
Spigot 1.12 will not load MassiveCore 2.12

### ISSUE THREAD

**Issue by Fiordhraoi** [MassiveCraft/MassiveCore#307]
**Describe your environment**
* MassiveCore version: 2.12
* Spigot version: 1.12
* Config pastebin: Completely default, but can paste again if needed.

**Steps to reproduce this bug**

  1. Installed Spigot 1.12 server from scratch
  2. Copied MassiveCore 2.12 jar into plugins folder
  3. Start Server, massivecore will not load

**Observed results**
Massive Core doesn't start, config files in mstore are never even created, etc.  The following error is on startup:
java.lang.UnsupportedOperationException: not implemented
        at com.massivecraft.massivecore.mixin.Mixin.notImplemented(Mixin.java:184) ~[?:?]
        at com.massivecraft.massivecore.nms.NmsItemStackCreate.create(NmsItemStackCreate.java:30) ~[?:?]
        at com.massivecraft.massivecore.item.WriterAbstractItemStack.createItemStack(WriterAbstractItemStack.java:49) ~[?:?]
        at com.massivecraft.massivecore.item.WriterAbstractItemStack.createOB(WriterAbstractItemStack.java:40) ~[?:?]
        at com.massivecraft.massivecore.item.WriterAbstract.setupSelf(WriterAbstract.java:218) ~[?:?]
        at com.massivecraft.massivecore.item.WriterAbstract.setActive(WriterAbstract.java:149) ~[?:?]
        at com.massivecraft.massivecore.Engine.setActive(Engine.java:108) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:248) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:227) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:236) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:212) ~[?:?]
        at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:238) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]

**Expected results**
Plugin never loads

**Comment by rautamiekka** [comment]
Are you sure you didn't make an error in the 'Expected results' part ?

**Comment by Fiordhraoi** [comment]
Whoops, you're right. Expected result would normally be that the plugin loads correctly. My brain was thinking "what's the expected result if they reproduce the error?"

**Comment by oloflarsson** [comment]
I can not get this to happen locally so I will need some help from you.

- What version of Java do you have installed?
- What version of Spigot are you using (/version)?
- What OS are you on?
- Are you using some kind of modified version of Spigot such as PaperSpigot?
- Does this happen on a fresh server with only MassiveCore installed and no other plugins?

Please go to `/mstore/massivecore_mconf/instance.json` set "debugActives" and "debugWriters" to true. Start the server and https://pastebin.com the entire log file here. That might allow us to see what's going wrong.

**Comment by natr566** [comment]
Hi I wish to help in this matter
so i built a blank server with this plugin and factions an put the log on pastebin here https://pastebin.com/embed_js/dkMF9jvt

Java - version 8 update 131 (build 1.8.0_131-b11)
Spigot version - version 1.12-R0.1-SNAPSHOT (listed at bottom of pastebin)
Os - windows 10

If there is any other info you need let me know, and i hope to help you in every way possible to get this plugin working again

**Comment by ulumulu1510** [comment]
I have tried to recreate this issue as well, et I was not able to do so:
Logs: https://pastebin.com/0BZscdvw

On of our team has managed to recreate it however, we work towards a solution with him. We still appreciate all help from the community.

**Comment by natr566** [comment]
And we the Community Love your guys plugins, and appreciate you guys are working hard to fix bugs.

**Comment by Fiordhraoi** [comment]
Hello!  Thank you for looking into this.

> What version of Java do you have installed?
I am running Java 8 Update 65

> What version of Spigot are you using (/version)?
This server is running CraftBukkit version git-Spigot-cd6ba67-a7d074c (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

> What OS are you on?
Windows 10

> Are you using some kind of modified version of Spigot such as PaperSpigot?
Nope, standard Spigot.

Does this happen on a fresh server with only MassiveCore installed and no other plugins?
Yes, I have no other plugins installed.

-----
As to the last part, I cannot edit the config files as they never generate.  The entire ./mstore directory is empty.

I'm glad someone else has replicated the issue.  Please let me know what else i can do to help, and thank you for the assistance.  :)

**Comment by ulumulu1510** [comment]
Cayorion (oloflarsson) has managed to locate and fix the bug. We will now proceed to test it and upload the fix asap, meaning later this day.

Explanation:
Apparently only servers were affected which had a space in their server names, which prompted an error in Guava 2.1. This issue is fixed in Guava 2.2, however 2.1 is being shipped with craftbukkit.

**Comment by thelegendmcturk** [comment]
[22:40:44] [Server thread/ERROR]: Error occurred while enabling MassiveCore v2.13.7 (Is it up to date?)
java.lang.RuntimeException: com.massivecraft.massivecore.MassiveCoreMConf : debugWriters
	at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateFields(MigratorUtil.java:335) ~[?:?]
	at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrate(MigratorUtil.java:199) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.loadFromRemoteFixed(Coll.java:298) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:731) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:882) ~[?:?]
	at com.massivecraft.massivecore.MassiveCoreMConfColl.setActive(MassiveCoreMConfColl.java:35) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:919) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:247) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:235) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:211) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
	at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:241) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2.jar:gi

**Comment by thelegendmcturk** [comment]
I have an interesting problem also. I dont know why,

I have the default config, I've updated it several times with the lastest project
but it gives the same result any time.
