### ISSUE TITLE
com.massivecraft.massivecore.mixin.Mixin.notImplemented(Mixin.java:184) ~[?:?]

### ISSUE THREAD

**Issue by mamoran** [MassiveCraft/MassiveCore#308]
**Affected Plugin**
MassiveCore

**Describe your environment**
* MassiveCore version: 2.12
* Spigot version: 1.12
* Config pastebin: 

**Steps to reproduce this bug**

  1. Issue command: java -Xms8192M -Xmx12200M -jar spigot-1.12.jar -o true

**Observed results**
C:\Program Files (x86)\Minecraft Server>java -Xms8192M -Xmx12200M -jar spigot-1.12.jar -o true
Loading libraries, please wait...
[01:14:09 INFO]: Starting minecraft server version 1.12
[01:14:09 INFO]: Loading properties
[01:14:09 WARN]: resource-pack-hash is deprecated and found along side resource-pack-sha1. resource-pack-hash will be ignored.
[01:14:09 INFO]: Default game type: CREATIVE
[01:14:09 INFO]: This server is running CraftBukkit version git-Spigot-0869666-03f1e37 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[01:14:09 INFO]: Debug logging is disabled
[01:14:09 INFO]: Server Ping Player Sample Count: 12
[01:14:09 INFO]: Using 4 threads for Netty based IO
[01:14:09 INFO]: Generating keypair
[01:14:10 INFO]: Starting Minecraft server on *:25565
[01:14:10 INFO]: Using default channel type
[01:14:10 INFO]: Set PluginClassLoader as parallel capable
[01:14:10 INFO]: [MuteManager] Loading MuteManager v0.16-51
[01:14:10 INFO]: [Elevators] Loading Elevators v1.0
[01:14:10 INFO]: [CapsLock] Loading CapsLock v1.0.4
[01:14:10 INFO]: [neoPaintingSwitch] Loading neoPaintingSwitch v1.371
[01:14:10 INFO]: [Vehicles] Loading Vehicles v8.4
[01:14:11 INFO]: [TuxTwoLib] Loading TuxTwoLib v1.11-b8
[01:14:11 INFO]: [AdvancedReport] Loading AdvancedReport v1.0.9
[01:14:11 INFO]: [BetterChairs] Loading BetterChairs v0.9.3
[01:14:11 INFO]: [GeneralLib] Loading GeneralLib v0.1.4
[01:14:11 INFO]: [TNT] Loading TNT v4.0
[01:14:11 INFO]: [CommandSpy] Loading CommandSpy v1.0
[01:14:11 INFO]: [MuteChat] Loading MuteChat v1.12
[01:14:11 INFO]: [TitleAPI] Loading TitleAPI v1.7.5
[01:14:11 INFO]: [LagMonitor] Loading LagMonitor v1.15
[01:14:11 INFO]: [CoreProtect] Loading CoreProtect v2.14.2
[01:14:11 INFO]: [NoCussing] Loading NoCussing v1.2
[01:14:11 INFO]: [SimpleJailr] Loading SimpleJailr v0.3
[01:14:11 INFO]: [dynmap] Loading dynmap v2.5-Dev201706100405
[01:14:11 INFO]: [dynmap] version=git-Spigot-0869666-03f1e37 (MC: 1.12)
[01:14:11 INFO]: [dynmap] Mod Support API available
[01:14:11 INFO]: [WorldEdit] Loading WorldEdit v6.1.3;7a097ca
[01:14:11 INFO]: [TimTheEnchanter] Loading TimTheEnchanter v3.0
[01:14:11 INFO]: [HeadHunter] Loading HeadHunter v1.7.1
[01:14:11 INFO]: [Essentials] Loading Essentials vTeamCity
[01:14:11 INFO]: [EasyInventory] Loading EasyInventory v1.0.9
[01:14:11 INFO]: [Launchpad] Loading Launchpad v1.0
[01:14:11 INFO]: [Toolbox] Loading Toolbox v1.0.6
[01:14:11 INFO]: [ActionBarAPI] Loading ActionBarAPI v1.5.3
[01:14:11 INFO]: [ProtocolLib] Loading ProtocolLib v4.3.0
[01:14:11 INFO]: [dynmap-mobs] Loading dynmap-mobs v1.3
[01:14:11 INFO]: [LibsDisguises] Loading LibsDisguises v9.1.1
[01:14:11 INFO]: [PlayerLinkReloaded] Loading PlayerLinkReloaded v11.0
[01:14:11 INFO]: [MyMOTD] Loading MyMOTD v0.2.3
[01:14:11 INFO]: [EssentialsChat] Loading EssentialsChat vTeamCity
[01:14:11 INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[01:14:11 INFO]: [CustomVillageTrades] Loading CustomVillageTrades v0.11.0
[01:14:11 INFO]: [iName] Loading iName v1.5
[01:14:11 INFO]: [Hugs] Loading Hugs v4
[01:14:11 INFO]: [Hugs] Has Loaded V4
[01:14:11 INFO]: [Vault] Loading Vault v1.5.6-b49
[01:14:11 INFO]: [MassiveCore] Loading MassiveCore v2.12.0
[01:14:11 INFO]: [EnjinMinecraftPlugin] Loading EnjinMinecraftPlugin v2.7.7
[01:14:11 INFO]: [Dynmap-Essentials] Loading Dynmap-Essentials v0.91-SNAPSHOT
[01:14:11 INFO]: [PerWorldInventory] Loading PerWorldInventory v1.10.0
[01:14:11 INFO]: [CreativeGates] Loading CreativeGates v2.12.0
[01:14:11 INFO]: [LWC] Loading LWC v1.8.2
[01:14:11 INFO]: [PlotSquared] Loading PlotSquared v3.5.0
[01:14:11 INFO]: [WorldGuard] Loading WorldGuard v6.1.2;e38d98d
[01:14:11 INFO]: [uCars] Loading uCars v19
[01:14:11 INFO]: [Factions] Loading Factions v2.12.0
[01:14:11 INFO]: [EssentialsProtect] Loading EssentialsProtect vTeamCity
[01:14:11 INFO]: [EssentialsGeoIP] Loading EssentialsGeoIP vTeamCity
[01:14:11 INFO]: [EssentialsAntiBuild] Loading EssentialsAntiBuild vTeamCity
[01:14:11 INFO]: [EnchantMore] Loading EnchantMore v3.0-SNAPSHOT
[01:14:11 INFO]: [AddLight] Loading AddLight v4.1.4
[01:14:11 INFO]: [MassiveBooks] Loading MassiveBooks v2.12.0
[01:14:11 INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[01:14:11 INFO]: [MassiveTickets] Loading MassiveTickets v2.12.0
[01:14:11 INFO]: [MassiveHat] Loading MassiveHat v2.12.0
[01:14:11 INFO]: [Orebfuscator4] Loading Orebfuscator4 v4.3.0
[01:14:11 INFO]: [MarriageMaster] Loading MarriageMaster v1.31.2
[01:14:11 INFO]: [SafeTrade] Loading SafeTrade v1.0.15
[01:14:11 INFO]: [Courier] Loading Courier v1.2.1
[01:14:11 INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5-b717
[01:14:11 INFO]: [Citizens] Loading Citizens v2.0.22-SNAPSHOT (build 1479)
[01:14:11 INFO]: [FactionsDynmap] Loading FactionsDynmap v2.12.0
[01:14:11 INFO]: [BiomeGenerator] Loading BiomeGenerator v3.4.0
[01:14:11 INFO]: [Plot2Dynmap] Loading Plot2Dynmap v3.3.2
[01:14:11 INFO]: [Multiverse-Portals] Loading Multiverse-Portals v2.5-b725
[01:14:11 INFO]: [Vampire] Loading Vampire v2.12.0
[01:14:11 INFO]: [Dynmap-Citizens2] Loading Dynmap-Citizens2 v0.30
[01:14:11 INFO]: [WorldGuardFix] Loading WorldGuardFix v1.7.3
[01:14:11 INFO]: [Builder] Loading Builder v0.9.1
[01:14:11 INFO]: [Movecraft] Loading Movecraft v3.1.X80
[01:14:11 INFO]: [Sentry] Loading Sentry v1.8.2
[01:14:11 INFO]: [Holograms] Loading Holograms v2.4.1-SNAPSHOT
[01:14:11 INFO]: [Blacksmith] Loading Blacksmith v1.1
[01:14:11 INFO]: [LeakParkour] Loading LeakParkour v2.3
[01:14:11 INFO]: [Alchemist] Loading Alchemist v1.1
[01:14:11 INFO]: [Kingdoms] Loading Kingdoms v13.2.26
[01:14:11 INFO]: [GeneralLib] Enabling GeneralLib v0.1.4
[01:14:11 INFO]: [ProtocolLib] Enabling ProtocolLib v4.3.0
[01:14:11 INFO]: [ProtocolLib] Started structure compiler thread.
[01:14:11 INFO]: [Vault] Enabling Vault v1.5.6-b49
[01:14:11 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[01:14:11 INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[01:14:11 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[01:14:11 INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[01:14:11 INFO]: [Vault] Enabled Version 1.5.6-b49
[01:14:11 INFO]: [MassiveCore] Enabling MassiveCore v2.12.0
[01:14:11 INFO]: [MassiveCore 2.12.0] === ENABLE START ===
[01:14:11 INFO]: [MassiveCore 2.12.0] Loading Cachefile datas...
[01:14:11 INFO]: [MassiveCore 2.12.0] Loading Onlineplayer datas...
[01:14:11 INFO]: [MassiveCore 2.12.0] Loading Registry datas...
[01:14:11 INFO]: [MassiveCore 2.12.0] Saving Cachefile...
[01:14:11 INFO]: [MassiveCore 2.12.0] Setup of IdUtil took 17ms.
[01:14:12 INFO]: [MassiveCore 2.12.0] Mixin NmsBasics set to Minecraft 1.7.10+ [1_7_R4+]
[01:14:12 INFO]: [MassiveCore 2.12.0] Mixin MixinEvent set to Default
[01:14:12 ERROR]: Error occurred while enabling MassiveCore v2.12.0 (Is it up to date?)
java.lang.UnsupportedOperationException: not implemented
        at com.massivecraft.massivecore.mixin.Mixin.notImplemented(Mixin.java:184) ~[?:?]
        at com.massivecraft.massivecore.nms.NmsItemStackCreate.create(NmsItemStackCreate.java:30) ~[?:?]
        at com.massivecraft.massivecore.item.WriterAbstractItemStack.createItemStack(WriterAbstractItemStack.java:49) ~[?:?]
        at com.massivecraft.massivecore.item.WriterAbstractItemStack.createOB(WriterAbstractItemStack.java:40) ~[?:?]
        at com.massivecraft.massivecore.item.WriterAbstract.setupSelf(WriterAbstract.java:218) ~[?:?]
        at com.massivecraft.massivecore.item.WriterAbstract.setActive(WriterAbstract.java:149) ~[?:?]
        at com.massivecraft.massivecore.Engine.setActive(Engine.java:108) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:248) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:227) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:236) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:212) ~[?:?]
        at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:238) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-0869666-03f1e37]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-0869666-03f1e37]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Expected results**
Massivecraft should load without error so that all the other related plugins can load too. Thanks!

**Comment by oloflarsson** [comment]
This issue is fixed in version 2.12.1.
