### ISSUE TITLE
major console spam

### ISSUE THREAD

**Issue by PhanaticD** [MassiveCraft/MassiveCore#320]
**Affected Plugin**
MassiveCombat

**Describe your environment**

* Affected Plugin version: 2.13.0
* MassiveCore version: 
* Spigot version:  git-Paper-1168 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
* Config pastebin: 

**Steps to reproduce this bug**

 happens on startup and continues after, I am assuming due to some sort of incompatibility with https://www.spigotmc.org/resources/factionsuuid.1035/

**Observed results**

this is spamming my logs
```
[04:19:56] [Server thread/INFO]: [MassiveCombat 2.13.0-SNAPSHOT] Integration Activation IntegrationFactions FAILED:
[04:19:56] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/massivecraft/factions/RelationParticipator
[04:19:56] [Server thread/WARN]:    at com.massivecraft.massivecombat.integration.factions.IntegrationFactions.getEngine(IntegrationFactions.java:26)
[04:19:56] [Server thread/WARN]:    at com.massivecraft.massivecore.Integration.getEngines(Integration.java:102)
[04:19:56] [Server thread/WARN]:    at com.massivecraft.massivecore.Integration.setIntegrationActiveEngines(Integration.java:93)
[04:19:56] [Server thread/WARN]:    at com.massivecraft.massivecore.Integration.setIntegrationActive(Integration.java:67)
[04:19:56] [Server thread/WARN]:    at com.massivecraft.massivecore.Integration.setIntegrationActive(Integration.java:84)
[04:19:56] [Server thread/WARN]:    at com.massivecraft.massivecore.Integration.run(Integration.java:158)
[04:19:56] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[04:19:56] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[04:19:56] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832)
[04:19:56] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[04:19:56] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[04:19:56] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[04:19:56] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[04:19:56] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.RelationParticipator
[04:19:56] [Server thread/WARN]:    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[04:19:56] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[04:19:56] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[04:19:56] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[04:19:56] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[04:19:56] [Server thread/WARN]:    ... 13 more
```

**Expected results**

**Comment by MarkehMe** [comment]
Factions 1.6 is not supported by MassiveCraft anymore, you will need to use the [Factions 2.13](https://www.spigotmc.org/resources/factions.1900/).

**Comment by PhanaticD** [comment]
okay then at least allow me to disable factions integration? I would like to be able to see my console and not have gigs of log files just because you want me to use a specific version of factions that I dont want to use
