### ISSUE TITLE
error after updating

### ISSUE THREAD

**Issue by PhanaticD** [MassiveCraft/MassiveCore#345]
I updated from 2.13.1 to 2.13.7 and get this error:

```
[04:14:12] [Server thread/INFO]: Enabling MassiveCore v2.13.7
[04:14:12] [Server thread/INFO]: [MassiveCore 2.13.7] === ENABLE START ===
[04:14:12] [Server thread/INFO]: [MassiveCore 2.13.7] Loading Cachefile datas...
[04:14:15] [Server thread/INFO]: [MassiveCore 2.13.7] Loading Onlineplayer datas...
[04:14:15] [Server thread/INFO]: [MassiveCore 2.13.7] Loading Registry datas...
[04:14:15] [Server thread/INFO]: [MassiveCore 2.13.7] Saving Cachefile...
[04:14:15] [Server thread/INFO]: [MassiveCore 2.13.7] Setup of IdUtil took 2789ms.
[04:14:16] [Server thread/INFO]: FAILURE FOR CLASS: class com.massivecraft.massivecore.MassiveCoreMConf
[04:14:16] [Server thread/ERROR]: Error occurred while enabling MassiveCore v2.13.7 (Is it up to date?)
java.lang.RuntimeException: com.massivecraft.massivecore.MassiveCoreMConf : mcstatsEnabled
    at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateFields(MigratorUtil.java:335) ~[?:?]
    at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrate(MigratorUtil.java:199) ~[?:?]
    at com.massivecraft.massivecore.store.Coll.loadFromRemoteFixed(Coll.java:298) ~[?:?]
    at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:731) ~[?:?]
    at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:882) ~[?:?]
    at com.massivecraft.massivecore.MassiveCoreMConfColl.setActive(MassiveCoreMConfColl.java:35) ~[?:?]
    at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:919) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:247) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:235) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:211) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
    at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:241) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1398]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:227) [patched_1.12.2.jar:git-Paper-1398]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1398]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[04:14:16] [Server thread/INFO]: Disabling MassiveCore v2.13.7
[04:14:16] [Server thread/INFO]: [MassiveCore 2.13.7] Disabled
[04:14:16] [Server thread/ERROR]: Error occurred while disabling MassiveCore v2.13.7 (Is it up to date?)
java.lang.NullPointerException: null
    at com.massivecraft.massivecore.MassiveCoreTaskDeleteFiles.run(MassiveCoreTaskDeleteFiles.java:21) ~[?:?]
    at com.massivecraft.massivecore.MassiveCore.onDisable(MassiveCore.java:305) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1398]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:227) [patched_1.12.2.jar:git-Paper-1398]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1398]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[04:14:16] [Server thread/INFO]: Enabling MassiveCombat v2.13.7
[04:14:16] [Server thread/INFO]: [MassiveCombat 2.13.7] === ENABLE START ===
[04:14:16] [Server thread/ERROR]: Error occurred while enabling MassiveCombat v2.13.7 (Is it up to date?)
java.lang.NullPointerException: null
    at com.massivecraft.massivecore.MassivePlugin.checkVersionSynchronization(MassivePlugin.java:117) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.onEnablePre(MassivePlugin.java:96) ~[?:?]
    at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:81) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1398]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1398]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:227) [patched_1.12.2.jar:git-Paper-1398]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1398]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[04:14:16] [Server thread/INFO]: Disabling MassiveCombat v2.13.7
[04:14:16] [Server thread/INFO]: [MassiveCombat 2.13.7] Disabled
```

**Comment by Techdude404Gaming** [comment]
I am getting the same problem...

**Plugin list:** 
![image](https://user-images.githubusercontent.com/25909830/41669351-36e80628-7477-11e8-9693-afc9f2083f4d.png)

**Isolated Error:** https://hastebin.com/ovitumewil.sql
**Full console log:** https://hastebin.com/iwocimagud.sql
