### ISSUE TITLE
Minecraft Spigot: Massive Core plugin and Factions plugin on version 1.12.2 doesnt work

### ISSUE THREAD

**Issue by Danyy0** [MassiveCraft/MassiveCore#360]
## Describe your Environment
- **Server Version: 1.12.2

## Steps to Reproduce this Bug
1. I downloaded Massive Core and Factions from here https://www.spigotmc.org/resources/factions.1900/ 
2. Then I unzipped the package and put the jar files in my plugins folder
3. Then when i started the server Massive Core and Factions didnt start and threw exceptions

## Observed Results
The error is like this
Massive Core

[23:35:13 ERROR]: Error occurred while enabling MassiveCore v2.14.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.massivecraft.massivecore.command.type.RegistryType.registerAll(RegistryType.java:369) ~[?:?]
        at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:234) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: private java.lang.String com.massivecraft.massivecore.item.DataBannerPattern.id
        at com.massivecraft.massivecore.command.editor.PropertyReflection.calcGetter(PropertyReflection.java:64) ~[?:?]
        at com.massivecraft.massivecore.command.editor.PropertyReflection.<init>(PropertyReflection.java:154) ~[?:?]
        at com.massivecraft.massivecore.command.editor.PropertyReflection.get(PropertyReflection.java:145) ~[?:?]
        at com.massivecraft.massivecore.command.editor.PropertyReflection.getAll(PropertyReflection.java:113) ~[?:?]
        at com.massivecraft.massivecore.command.type.combined.TypeCombined.<init>(TypeCombined.java:101) ~[?:?]
        at com.massivecraft.massivecore.command.type.combined.TypeDataBannerPattern.<init>(TypeDataBannerPattern.java:16) ~[?:?]
        at com.massivecraft.massivecore.command.type.combined.TypeDataBannerPattern.<clinit>(TypeDataBannerPattern.java:11) ~[?:?]
        ... 11 more

 and Factions

[23:35:21 ERROR]: Error occurred while enabling Factions v2.14.0 (Is it up to date?)
java.lang.NullPointerException: null
        at com.massivecraft.massivecore.MassivePlugin.checkVersionSynchronization(MassivePlugin.java:117) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnablePre(MassivePlugin.java:96) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:81) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

## Expected Results
I expected that the plugin wont throw exceptions and work properly so i can use Factions plugin...

**Comment by crazybytes** [comment]
Same here...
Compiled from scratch, overcome many obstacles. Succes .jar files, put in bukkit mod dir, same failures....
