### ISSUE TITLE
Help ! my server is down...

### ISSUE THREAD

**Issue by Tryder34** [MassiveCraft/MassiveCore#368]
[23:54:27 INFO]: [MassiveCore 2.8.5] If you use 1.8.X or above, please report this error at https://github.com/MassiveCraft/MassiveCore/issues
[23:54:27 WARN]: com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket$VersionIncompatibleException: Your current bukkit version seems to be incompatible with this library
[23:54:27 WARN]: at com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1401)
[23:54:27 WARN]: at com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket.getVersion(ParticleEffect.java:1414)
[23:54:27 WARN]: at com.massivecraft.massivecore.nms.NmsAbstract.getCurrentVersion(NmsAbstract.java:63)
[23:54:27 WARN]: at com.massivecraft.massivecore.nms.NmsAbstract.isAvailableForCurrentVersion(NmsAbstract.java:73)
[23:54:27 WARN]: at com.massivecraft.massivecore.nms.NmsAbstract.<init>(NmsAbstract.java:33)
[23:54:27 WARN]: at com.massivecraft.massivecore.nms.NmsPacket.<init>(NmsPacket.java:15)
[23:54:27 WARN]: at com.massivecraft.massivecore.nms.NmsPacket.<clinit>(NmsPacket.java:21)
[23:54:27 WARN]: at com.massivecraft.massivecore.mixin.TitleMixinDefault.isTitlesAvailable(TitleMixinDefault.java:41)
[23:54:27 WARN]: at com.massivecraft.massivecore.mixin.Mixin.isTitlesAvailable(Mixin.java:417)
[23:54:27 WARN]: at com.massivecraft.factions.entity.MPlayer.isTerritoryInfoTitles(MPlayer.java:576)
[23:54:27 WARN]: at com.massivecraft.factions.entity.MPlayer.isDefault(MPlayer.java:77)
[23:54:27 WARN]: at com.massivecraft.massivecore.store.Coll.isDefault(Coll.java:200)
[23:54:27 WARN]: at com.massivecraft.massivecore.store.Coll.saveToRemoteFixed(Coll.java:469)
[23:54:27 WARN]: at com.massivecraft.massivecore.store.Coll.syncIdFixed(Coll.java:702)
[23:54:27 WARN]: at com.massivecraft.massivecore.store.CollAbstract.syncIdFixed(CollAbstract.java:236)
[23:54:27 WARN]: at com.massivecraft.massivecore.store.Coll.syncIdentified(Coll.java:896)
[23:54:27 WARN]: at com.massivecraft.massivecore.store.Coll.onTick(Coll.java:930)
[23:54:27 WARN]: at com.massivecraft.massivecore.store.SenderColl.onTick(SenderColl.java:38)
[23:54:27 WARN]: at com.massivecraft.factions.entity.MPlayerColl.onTick(MPlayerColl.java:34)
[23:54:27 WARN]: at com.massivecraft.massivecore.engine.EngineMassiveCoreCollTick.run(EngineMassiveCoreCollTick.java:43)
[23:54:27 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[23:54:27 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[23:54:27 WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
[23:54:27 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[23:54:27 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[23:54:27 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[23:54:27 WARN]: at java.lang.Thread.run(Thread.java:748)
[23:54:27 WARN]: Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutWorldParticles
[23:54:27 WARN]: at java.lang.Class.forName0(Native Method)
[23:54:27 WARN]: at java.lang.Class.forName(Class.java:264)
[23:54:27 WARN]: at com.massivecraft.massivecore.particleeffect.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:414)
[23:54:27 WARN]: at com.massivecraft.massivecore.particleeffect.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1395)
[23:54:27 WARN]: ... 26 more

please help me...

**Comment by markhughes** [comment]
You need to upgrade to Factions V3

https://www.spigotmc.org/resources/factions3-for-1-13.63602/
